require 'rubygems'
require 'stringio'
require 'test/unit'
require 'active_record'
require 'mocha'
require 'lib/active_record_connector'
require 'config/schema'
require File.dirname(__FILE__) + '/../lib/sieve'